server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  thymeleaf:
#    suffix: .jsp
#    prefix:
#      classpath: /templates/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.jt.common.po
  configuration:
    map-underscore-to-camel-case: true

#mybatis-plus: #mybatis-plus
#  type-aliases-package: com.jt.sso.pojo
#  mapper-locations: classpath:/mybatis/mappers/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
